### ISSUE TITLE
SqlDataProvider and Npgsql do not work with Postgresql db

### ISSUE THREAD

**Issue by qbpd** [fsprojects/SQLProvider#373]
### Description

With a new project, I get an error when following the instructions on the PostgreSQL Provider page

### Repro steps

created new console app.
used nuget to install FSharp.Data, SQLProvider, and Npgsql

Code:
```
open FSharp.Data
open FSharp.Data.Sql

let [<Literal>] connString = "Host=localhost;Port=5432;Database=xxx;Username=xxxx;Password=xxxx;"
let [<Literal>] dbVendor = Common.DatabaseProviderTypes.POSTGRESQL
let [<Literal>] resPath = @"../packages/Npgsql.3.2.0/lib/net451/"
let [<Literal>] indivAmount = 1000
let [<Literal>] useOptTypes = true
type dbSchema = SqlDataProvider<dbVendor,connString,"",resPath,indivAmount,useOptTypes>

```
### Actual behavior

Compiler error:

The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=cc7......' or one of its dependencies. The system cannot find the file specified. 

This is especially peculiar to me since Npgsql installs System.Threading.Tasks.Extensions.4.3.0 and I have located in my packages folder. There's also no Version 4.1.0.0 that exists in nuget.

### Related information 

* Postgresql 9.4.10
* Windows 10 x64
* .target framework: 4.5.2 (also re-tried with 4.6.1)
* FSharp 4.4.0.0

**Comment by hermesxgjini** [comment]
i had the same issue, try using **Npgsql.3.1.0** package instead of **Npgsql.3.2.0**

**Comment by s952163** [comment]
This has something to do with how npgsql expects .NET Standard 1.3 when it's actually on the full framework. I think this error still occurs.

**Comment by MaybeSacred** [comment]
I had a similar issue with a new project and Postgresql database that was also resolved by switching from Npgsql.3.2.0 to Npgsql.3.1.0. However, in my case, the type provider did not emit a compiler error or PossibleError property on the context object; it silently failed to provide any types on the context object.

-  Postgresql 9.6.3
-  Windows 10 x64
-  Target framework: 4.6.1
-  FSharp 4.4.1.0

**Comment by Thorium** [comment]
Yes, Postgres 3.2 is depending on Nuget package System.Threading.Tasks.Extensions and our dynamic assembly loading failed to find sub-assemblies. We can add some extra paths to look for the dll (the reference path and executing assembly path), but not much else we can do.

**Comment by MatthiasWeiser** [comment]
The problem still exists - I received a TypeLoaderException when upgrading to the latest 3.2 Npgsql - rolling back to Npgsql 3.1.10 helped.
The Type Loader exception pointed to an old version of System.Threading.Tasks.Extensions.

**Comment by Douse84** [comment]
Can confirm, this issue still persists.

Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040).

Confirmed that I had 4.3.0 installed and available.

Rolled back to 3.1.10.

**Comment by Douse84** [comment]
So I may have isolated this to EntityFramework6.Npgsql as I have other applications using the latest version of NpgSql just fine. Not sure if this is helpful at all....

**Comment by Thorium** [comment]
Can you add explicit reference to your project to correct version of `System.Threading.Tasks.Extensions.dll` or copy the dll to either your `resPath` or bin folder? "Correct version" meaning the version that NpgSql tries to reference. There is a dependency in the NpgSql NuGet package.

**Comment by Douse84** [comment]
Thanks for the suggestion, but I would rather avoid this manual fix if I could. I am going to leave 3.1.10 for now and remove my applications dependency on EntityFramework6.Npgsql.

**Comment by Thorium** [comment]
Ok, probably the reason is that we are loading the System.Threading.Tasks.Extensions.dll on runtime but we should do a runtime-assembly-binding-redirect as NuGet may load a different version than the Npgsql referenced. I'll see what I can do...

**Comment by Thorium** [comment]
Should be fixed in 1.1.18.

**Comment by drivehappy** [comment]
This is still occurring for me with 1.1.18:
```
The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.Details: Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
```
In fact it seems to now occur with Npgsql 3.1.10 after upgrading to 1.1.18.

Downgrading to SQLProvider 1.1.11 and Npgsql 3.1.10 seems to be the only way to build successfully.

**Comment by Thorium** [comment]
With 1.1.18, can you:
- Download the System.Threading.Tasks.Extensions Nuget-package and add a reference to your project.
- Put the System.Threading.Tasks.Extensions.dll to the referencePath where is the Npgsql.dll already

**Comment by drivehappy** [comment]
Unfortunately still having trouble:

1. Nuget installed SqlProvider 1.1.18 and Npgsql 3.2.5
2. System.Threading.Tasks.Extensions is already included as a dependency with Npgsql, so version 4.3.0 is already a reference in my project
3. I copied the System.Threading.Tasks.Extensions.dll to the same path as my referencePath that includes Npgsql.dll, e.g.:
    ```
    type SqlType =
    SqlDataProvider<
        Common.DatabaseProviderTypes.POSTGRESQL,
        "Host=localhost;Port=5433;Database=OMITTED;Username=OMITTED;Password=OMITTED",
        "",
        @"OMITTED\packages\Npgsql.3.2.5\lib\net451\Npgsql.dll",
        1000,
        true>
   ```

   So I copied System.Threading.Tasks.Extensions.dll into `OMITTED\packages\Npgsql.3.2.5\lib\net451\`
4. Still receiving the error about unable to find System.Threading.Tasks.Extensions.dll 4.1.0.0

I'm confused as to the version numbering going on as well, I would have assumed there would be a nuget package of 4.1.0 for System.Threading.Tasks.Extensions, but all I see are 4.0.0, 4.3.0, and 4.4.0 (of which I tried all 3 explicitly just in case).

I'm also confused by your comment regarding your `runtime-binding-redirect` - does that mean I need to do something on my side, or that it should working automagically for me?

**Comment by Thorium** [comment]
Reference path is path, not filename. Try just the directory. I guess we could fix it to accept both.

**Comment by drivehappy** [comment]
Ah, that was it - the reference path used to work with the filename present in 1.1.11. I also noticed that it still had issues if I had a trailing backslash in the path as well.

Thanks for the help.

**Comment by laygr** [comment]
I fixed the trailing backslash problem by using triple double quotes, like this:
@"""OMITTED\packages\Npgsql.3.2.5\lib\net451\"""

**Comment by sandeepc24** [comment]
I am getting this error with dotnet core 2.
```
Error	FS3033	The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
Details: 
Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
Could not load file or assembly 'System.Data.Common, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

Here are the project nugets

![image](https://user-images.githubusercontent.com/4897654/34510521-68d8b69c-f0b9-11e7-9194-7b724b894131.png)

**Comment by Thorium** [comment]
Try adding those packages as in here: https://github.com/fsprojects/SQLProvider/blob/master/tests/SqlProvider.Core.Tests/Postgres/SqlProvider.Core.Tests.fsproj

**Comment by GiorgioG** [comment]
Still seeing this issue with a .NET Core 2.1 project, trying to use SQLProvider 1.1.43 with npgsql 4.0.0.

![image](https://user-images.githubusercontent.com/968113/41504232-cfd2edda-71b6-11e8-95c8-0eec86ab594c.png)

Trying to add the System.Threading.Tasks.Extensions NuGet package (v4.5.0) yields the exact same bug.

**Comment by SrancsikAtBitrise** [comment]
Still seeing this issue: SQLProvider 1.1.52 and Npgsql 4.0.3.

![screen shot 2018-09-25 at 12 36 03](https://user-images.githubusercontent.com/39155393/46009380-a8517f80-c0bf-11e8-9bca-47fb998b86f1.png)

**Comment by i3anaan** [comment]
Still having this issue as well.

**Comment by mushishi78** [comment]
Had this problem today with 4.0.9. Downgraded to 3.1.0 seems to work. @Thorium Seems like this ticket shouldn't be closed.

**Comment by lreiner** [comment]
> 
> 
> i had the same issue, try using **Npgsql.3.1.0** package instead of **Npgsql.3.2.0**

This litterly safed my life. Tried like 3 hours to find out why I couldnt connect to my PostgreSQL Server anymore. It always gave me this error: `Can't resolve reference to Tasks.Extensions` . Reinstalled Npgsql.4.0.1 and it added the missing references. Now its working fine again. Thanks bro!
